# Generated by Django 6.0.5 on 2026-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_is_credited'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='electronic_status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdp_last_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdp_last_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdp_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdp_reject_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdp_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
