# Generated by Django 6.0.5 on 2026-05-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_electronic_status_invoice_pdp_last_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='e_reporting_last_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_reporting_last_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_reporting_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_reporting_rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_reporting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_reporting_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_reporting_status',
            field=models.CharField(default='NOT_REQUIRED', max_length=20),
        ),
    ]
